#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE 0

// Poké Balls
#define SECTION_POKE_BALLS(x) (0 + x)
#define ITEM_POKE_BALL SECTION_POKE_BALLS(1)
#define ITEM_GREAT_BALL SECTION_POKE_BALLS(2)
#define ITEM_ULTRA_BALL SECTION_POKE_BALLS(3)
#define ITEM_MASTER_BALL SECTION_POKE_BALLS(4)
#define ITEM_PREMIER_BALL SECTION_POKE_BALLS(5)
#define ITEM_HEAL_BALL SECTION_POKE_BALLS(6)
#define ITEM_NET_BALL SECTION_POKE_BALLS(7)
#define ITEM_NEST_BALL SECTION_POKE_BALLS(8)
#define ITEM_DIVE_BALL SECTION_POKE_BALLS(9)
#define ITEM_DUSK_BALL SECTION_POKE_BALLS(10)
#define ITEM_TIMER_BALL SECTION_POKE_BALLS(11)
#define ITEM_QUICK_BALL SECTION_POKE_BALLS(12)
#define ITEM_REPEAT_BALL SECTION_POKE_BALLS(13)
#define ITEM_LUXURY_BALL SECTION_POKE_BALLS(14)
#define ITEM_LEVEL_BALL SECTION_POKE_BALLS(15)
#define ITEM_LURE_BALL SECTION_POKE_BALLS(16)
#define ITEM_MOON_BALL SECTION_POKE_BALLS(17)
#define ITEM_FRIEND_BALL SECTION_POKE_BALLS(18)
#define ITEM_LOVE_BALL SECTION_POKE_BALLS(19)
#define ITEM_FAST_BALL SECTION_POKE_BALLS(20)
#define ITEM_HEAVY_BALL SECTION_POKE_BALLS(21)
#define ITEM_DREAM_BALL SECTION_POKE_BALLS(22)
#define ITEM_SAFARI_BALL SECTION_POKE_BALLS(23)
#define ITEM_SPORT_BALL SECTION_POKE_BALLS(24)
#define ITEM_PARK_BALL SECTION_POKE_BALLS(25)
#define ITEM_BEAST_BALL SECTION_POKE_BALLS(26)
#define ITEM_CHERISH_BALL SECTION_POKE_BALLS(27)

// Note: If moving ball IDs around, updating FIRST_BALL/LAST_BALL is not sufficient
//       Several places expect the ball IDs to be first and contiguous (e.g. MON_DATA_POKEBALL)
//       If adding new balls, it's easiest to insert them after the last ball and increment the below IDs (and removing ITEM_034 for example)
#define FIRST_BALL ITEM_POKE_BALL
#define LAST_BALL  ITEM_CHERISH_BALL

// Medicine
#define SECTION_MEDICINE(x) (x + SECTION_POKE_BALLS(27))
#define ITEM_POTION SECTION_MEDICINE(1)
#define ITEM_SUPER_POTION SECTION_MEDICINE(2)
#define ITEM_HYPER_POTION SECTION_MEDICINE(3)
#define ITEM_MAX_POTION SECTION_MEDICINE(4)
#define ITEM_FULL_RESTORE SECTION_MEDICINE(5)
#define ITEM_REVIVE SECTION_MEDICINE(6)
#define ITEM_MAX_REVIVE SECTION_MEDICINE(7)
#define ITEM_FRESH_WATER SECTION_MEDICINE(8)
#define ITEM_SODA_POP SECTION_MEDICINE(9)
#define ITEM_LEMONADE SECTION_MEDICINE(10)
#define ITEM_MOOMOO_MILK SECTION_MEDICINE(11)
#define ITEM_ENERGY_POWDER SECTION_MEDICINE(12)
#define ITEM_ENERGYPOWDER ITEM_ENERGY_POWDER // Pre-Gen VI name
#define ITEM_ENERGY_ROOT SECTION_MEDICINE(13)
#define ITEM_HEAL_POWDER SECTION_MEDICINE(14)
#define ITEM_REVIVAL_HERB SECTION_MEDICINE(15)
#define ITEM_ANTIDOTE SECTION_MEDICINE(16)
#define ITEM_PARALYZE_HEAL SECTION_MEDICINE(17)
#define ITEM_PARLYZ_HEAL ITEM_PARALYZE_HEAL // Pre-Gen VI name
#define ITEM_BURN_HEAL SECTION_MEDICINE(18)
#define ITEM_ICE_HEAL SECTION_MEDICINE(19)
#define ITEM_AWAKENING SECTION_MEDICINE(20)
#define ITEM_FULL_HEAL SECTION_MEDICINE(21)
#define ITEM_ETHER SECTION_MEDICINE(22)
#define ITEM_MAX_ETHER SECTION_MEDICINE(23)
#define ITEM_ELIXIR SECTION_MEDICINE(24)
#define ITEM_ELIXER ITEM_ELIXIR // Pre-Gen III name
#define ITEM_MAX_ELIXIR SECTION_MEDICINE(25)
#define ITEM_MAX_ELIXER ITEM_MAX_ELIXIR // Pre-Gen III name
#define ITEM_BERRY_JUICE SECTION_MEDICINE(26)
#define ITEM_SACRED_ASH SECTION_MEDICINE(27)
#define ITEM_SWEET_HEART SECTION_MEDICINE(28)
#define ITEM_MAX_HONEY SECTION_MEDICINE(29)

// Regional Specialties
#define SECTION_REGIONAL_SPECIALTIES(x) (x + SECTION_MEDICINE(29))
#define ITEM_PEWTER_CRUNCHIES SECTION_REGIONAL_SPECIALTIES(1)
#define ITEM_RAGE_CANDY_BAR SECTION_REGIONAL_SPECIALTIES(2)
#define ITEM_RAGECANDYBAR ITEM_RAGE_CANDY_BAR // Pre-Gen VI name
#define ITEM_LAVA_COOKIE SECTION_REGIONAL_SPECIALTIES(3)
#define ITEM_OLD_GATEAU SECTION_REGIONAL_SPECIALTIES(4)
#define ITEM_CASTELIACONE SECTION_REGIONAL_SPECIALTIES(5)
#define ITEM_LUMIOSE_GALETTE SECTION_REGIONAL_SPECIALTIES(6)
#define ITEM_SHALOUR_SABLE SECTION_REGIONAL_SPECIALTIES(7)
#define ITEM_BIG_MALASADA SECTION_REGIONAL_SPECIALTIES(8)

// Vitamins
#define SECTION_VITAMINS(x) (x + SECTION_REGIONAL_SPECIALTIES(8))
#define ITEM_HP_UP SECTION_VITAMINS(1)
#define ITEM_PROTEIN SECTION_VITAMINS(2)
#define ITEM_IRON SECTION_VITAMINS(3)
#define ITEM_CALCIUM SECTION_VITAMINS(4)
#define ITEM_ZINC SECTION_VITAMINS(5)
#define ITEM_CARBOS SECTION_VITAMINS(6)
#define ITEM_PP_UP SECTION_VITAMINS(7)
#define ITEM_PP_MAX SECTION_VITAMINS(8)

// EV Feathers
#define SECTION_EV_FEATHERS(x) (x + SECTION_VITAMINS(8))
#define ITEM_HEALTH_FEATHER SECTION_EV_FEATHERS(1)
#define ITEM_HEALTH_WING ITEM_HEALTH_FEATHER // Pre-Gen VIII name
#define ITEM_MUSCLE_FEATHER SECTION_EV_FEATHERS(2)
#define ITEM_MUSCLE_WING ITEM_MUSCLE_FEATHER // Pre-Gen VIII name
#define ITEM_RESIST_FEATHER SECTION_EV_FEATHERS(3)
#define ITEM_RESIST_WING ITEM_RESIST_FEATHER // Pre-Gen VIII name
#define ITEM_GENIUS_FEATHER SECTION_EV_FEATHERS(4)
#define ITEM_GENIUS_WING ITEM_GENIUS_FEATHER // Pre-Gen VIII name
#define ITEM_CLEVER_FEATHER SECTION_EV_FEATHERS(5)
#define ITEM_CLEVER_WING ITEM_CLEVER_FEATHER // Pre-Gen VIII name
#define ITEM_SWIFT_FEATHER SECTION_EV_FEATHERS(6)
#define ITEM_SWIFT_WING ITEM_SWIFT_FEATHER // Pre-Gen VIII name

// Ability Modifiers
#define SECTION_ABILITIES(x) (x + SECTION_EV_FEATHERS(6))
#define ITEM_ABILITY_CAPSULE SECTION_ABILITIES(1)
#define ITEM_ABILITY_PATCH SECTION_ABILITIES(2)

// Mints
#define SECTION_MINTS(x) (x + SECTION_ABILITIES(2))
#define ITEM_LONELY_MINT SECTION_MINTS(1)
#define ITEM_ADAMANT_MINT SECTION_MINTS(2)
#define ITEM_NAUGHTY_MINT SECTION_MINTS(3)
#define ITEM_BRAVE_MINT SECTION_MINTS(4)
#define ITEM_BOLD_MINT SECTION_MINTS(5)
#define ITEM_IMPISH_MINT SECTION_MINTS(6)
#define ITEM_LAX_MINT SECTION_MINTS(7)
#define ITEM_RELAXED_MINT SECTION_MINTS(8)
#define ITEM_MODEST_MINT SECTION_MINTS(9)
#define ITEM_MILD_MINT SECTION_MINTS(10)
#define ITEM_RASH_MINT SECTION_MINTS(11)
#define ITEM_QUIET_MINT SECTION_MINTS(12)
#define ITEM_CALM_MINT SECTION_MINTS(13)
#define ITEM_GENTLE_MINT SECTION_MINTS(14)
#define ITEM_CAREFUL_MINT SECTION_MINTS(15)
#define ITEM_SASSY_MINT SECTION_MINTS(16)
#define ITEM_TIMID_MINT SECTION_MINTS(17)
#define ITEM_HASTY_MINT SECTION_MINTS(18)
#define ITEM_JOLLY_MINT SECTION_MINTS(19)
#define ITEM_NAIVE_MINT SECTION_MINTS(20)
#define ITEM_SERIOUS_MINT SECTION_MINTS(21)

// Candy
#define SECTION_CANDIES(x) (x + SECTION_MINTS(21))
#define ITEM_RARE_CANDY SECTION_CANDIES(1)
#define ITEM_EXP_CANDY_XS SECTION_CANDIES(2)
#define ITEM_EXP_CANDY_S SECTION_CANDIES(3)
#define ITEM_EXP_CANDY_M SECTION_CANDIES(4)
#define ITEM_EXP_CANDY_L SECTION_CANDIES(5)
#define ITEM_EXP_CANDY_XL SECTION_CANDIES(6)
#define ITEM_DYNAMAX_CANDY SECTION_CANDIES(7)

// Medicinal Flutes
#define SECTION_FLUTES(x) (x + SECTION_CANDIES(7))
#define ITEM_BLUE_FLUTE SECTION_FLUTES(1)
#define ITEM_YELLOW_FLUTE SECTION_FLUTES(2)
#define ITEM_RED_FLUTE SECTION_FLUTES(3)

// Encounter-modifying Flutes
#define ITEM_BLACK_FLUTE SECTION_FLUTES(4)
#define ITEM_WHITE_FLUTE SECTION_FLUTES(5)

// Encounter Modifiers
#define SECTION_ENCOUNTER_MODIFIERS(x) (x + SECTION_FLUTES(5))
#define ITEM_REPEL SECTION_ENCOUNTER_MODIFIERS(1)
#define ITEM_SUPER_REPEL SECTION_ENCOUNTER_MODIFIERS(2)
#define ITEM_MAX_REPEL SECTION_ENCOUNTER_MODIFIERS(3)
#define ITEM_LURE SECTION_ENCOUNTER_MODIFIERS(4)
#define ITEM_SUPER_LURE SECTION_ENCOUNTER_MODIFIERS(5)
#define ITEM_MAX_LURE SECTION_ENCOUNTER_MODIFIERS(6)

#define ITEM_ESCAPE_ROPE SECTION_ENCOUNTER_MODIFIERS(7)

// X Items
#define SECTION_BATTLE_ITEMS(x) (x + SECTION_ENCOUNTER_MODIFIERS(7))
#define ITEM_X_ATTACK SECTION_BATTLE_ITEMS(1)
#define ITEM_X_DEFENSE SECTION_BATTLE_ITEMS(2)
#define ITEM_X_DEFEND ITEM_X_DEFENSE // Pre-Gen VI name
#define ITEM_X_SP_ATK SECTION_BATTLE_ITEMS(3)
#define ITEM_X_SPECIAL ITEM_X_SP_ATK // Pre-Gen VI name
#define ITEM_X_SP_DEF SECTION_BATTLE_ITEMS(4)
#define ITEM_X_SPEED SECTION_BATTLE_ITEMS(5)
#define ITEM_X_ACCURACY SECTION_BATTLE_ITEMS(6)

#define ITEM_DIRE_HIT SECTION_BATTLE_ITEMS(7)
#define ITEM_GUARD_SPEC SECTION_BATTLE_ITEMS(8)

// Escape Items
#define ITEM_POKE_DOLL SECTION_BATTLE_ITEMS(9)
#define ITEM_FLUFFY_TAIL SECTION_BATTLE_ITEMS(10)
#define ITEM_POKE_TOY SECTION_BATTLE_ITEMS(11)

#define ITEM_MAX_MUSHROOMS SECTION_BATTLE_ITEMS(12)

// Treasures
#define SECTION_TREASURES(x) (x + SECTION_BATTLE_ITEMS(12))
#define ITEM_BOTTLE_CAP SECTION_TREASURES(1)
#define ITEM_GOLD_BOTTLE_CAP SECTION_TREASURES(2)
#define ITEM_NUGGET SECTION_TREASURES(3)
#define ITEM_BIG_NUGGET SECTION_TREASURES(4)
#define ITEM_TINY_MUSHROOM SECTION_TREASURES(5)
#define ITEM_TINYMUSHROOM ITEM_TINY_MUSHROOM // Pre-Gen VI name
#define ITEM_BIG_MUSHROOM SECTION_TREASURES(6)
#define ITEM_BALM_MUSHROOM SECTION_TREASURES(7)
#define ITEM_BALMMUSHROOM ITEM_BALM_MUSHROOM // Pre-Gen VI name
#define ITEM_PEARL SECTION_TREASURES(8)
#define ITEM_BIG_PEARL SECTION_TREASURES(9)
#define ITEM_PEARL_STRING SECTION_TREASURES(10)
#define ITEM_STARDUST SECTION_TREASURES(11)
#define ITEM_STAR_PIECE SECTION_TREASURES(12)
#define ITEM_COMET_SHARD SECTION_TREASURES(13)
#define ITEM_SHOAL_SALT SECTION_TREASURES(14)
#define ITEM_SHOAL_SHELL SECTION_TREASURES(15)
#define ITEM_RED_SHARD SECTION_TREASURES(16)
#define ITEM_BLUE_SHARD SECTION_TREASURES(17)
#define ITEM_YELLOW_SHARD SECTION_TREASURES(18)
#define ITEM_GREEN_SHARD SECTION_TREASURES(19)
#define ITEM_HEART_SCALE SECTION_TREASURES(20)
#define ITEM_HONEY SECTION_TREASURES(21)
#define ITEM_RARE_BONE SECTION_TREASURES(22)
#define ITEM_ODD_KEYSTONE SECTION_TREASURES(23)
#define ITEM_PRETTY_FEATHER SECTION_TREASURES(24)
#define ITEM_PRETTY_WING ITEM_PRETTY_FEATHER // Pre-Gen VIII name
#define ITEM_RELIC_COPPER SECTION_TREASURES(25)
#define ITEM_RELIC_SILVER SECTION_TREASURES(26)
#define ITEM_RELIC_GOLD SECTION_TREASURES(27)
#define ITEM_RELIC_VASE SECTION_TREASURES(28)
#define ITEM_RELIC_BAND SECTION_TREASURES(29)
#define ITEM_RELIC_STATUE SECTION_TREASURES(30)
#define ITEM_RELIC_CROWN SECTION_TREASURES(31)
#define ITEM_STRANGE_SOUVENIR SECTION_TREASURES(32)

// Fossils
#define SECTION_FOSSILS(x) (x + SECTION_TREASURES(32))
#define ITEM_HELIX_FOSSIL SECTION_FOSSILS(1)
#define ITEM_DOME_FOSSIL SECTION_FOSSILS(2)
#define ITEM_OLD_AMBER SECTION_FOSSILS(3)
#define ITEM_ROOT_FOSSIL SECTION_FOSSILS(4)
#define ITEM_CLAW_FOSSIL SECTION_FOSSILS(5)
#define ITEM_ARMOR_FOSSIL SECTION_FOSSILS(6)
#define ITEM_SKULL_FOSSIL SECTION_FOSSILS(7)
#define ITEM_COVER_FOSSIL SECTION_FOSSILS(8)
#define ITEM_PLUME_FOSSIL SECTION_FOSSILS(9)
#define ITEM_JAW_FOSSIL SECTION_FOSSILS(10)
#define ITEM_SAIL_FOSSIL SECTION_FOSSILS(11)
#define ITEM_FOSSILIZED_BIRD SECTION_FOSSILS(12)
#define ITEM_FOSSILIZED_FISH SECTION_FOSSILS(13)
#define ITEM_FOSSILIZED_DRAKE SECTION_FOSSILS(14)
#define ITEM_FOSSILIZED_DINO SECTION_FOSSILS(15)
// Mulch
#define SECTION_MULCH(x) (x + SECTION_FOSSILS(15))
#define ITEM_GROWTH_MULCH SECTION_MULCH(1)
#define ITEM_DAMP_MULCH SECTION_MULCH(2)
#define ITEM_STABLE_MULCH SECTION_MULCH(3)
#define ITEM_GOOEY_MULCH SECTION_MULCH(4)
#define ITEM_RICH_MULCH SECTION_MULCH(5)
#define ITEM_SURPRISE_MULCH SECTION_MULCH(6)
#define ITEM_BOOST_MULCH SECTION_MULCH(7)
#define ITEM_AMAZE_MULCH SECTION_MULCH(8)

// Apricorns
#define SECTION_APRICORNS(x) (x + SECTION_MULCH(8))
#define ITEM_RED_APRICORN SECTION_APRICORNS(1)
#define ITEM_BLUE_APRICORN SECTION_APRICORNS(2)
#define ITEM_BLU_APRICORN ITEM_BLUE_APRICORN // Pre-Gen VI name
#define ITEM_YELLOW_APRICORN SECTION_APRICORNS(3)
#define ITEM_YLW_APRICORN ITEM_YELLOW_APRICORN // Pre-Gen VI name
#define ITEM_GREEN_APRICORN SECTION_APRICORNS(4)
#define ITEM_GRN_APRICORN ITEM_GREEN_APRICORN // Pre-Gen VI name
#define ITEM_PINK_APRICORN SECTION_APRICORNS(5)
#define ITEM_PNK_APRICORN ITEM_PINK_APRICORN // Pre-Gen VI name
#define ITEM_WHITE_APRICORN SECTION_APRICORNS(6)
#define ITEM_WHT_APRICORN ITEM_WHITE_APRICORN // Pre-Gen VI name
#define ITEM_BLACK_APRICORN SECTION_APRICORNS(7)
#define ITEM_BLK_APRICORN ITEM_BLACK_APRICORN // Pre-Gen VI name

// Gen VIII Specials
#define SECTION_GEN_VIII_SPECIALS(x) (x + SECTION_APRICORNS(7))
#define ITEM_WISHING_PIECE SECTION_GEN_VIII_SPECIALS(1)
#define ITEM_GALARICA_TWIG SECTION_GEN_VIII_SPECIALS(2)
#define ITEM_ARMORITE_ORE SECTION_GEN_VIII_SPECIALS(3)
#define ITEM_DYNITE_ORE SECTION_GEN_VIII_SPECIALS(4)

// Mail
#define SECTION_MAIL(x) (x + SECTION_GEN_VIII_SPECIALS(4))
#define ITEM_ORANGE_MAIL SECTION_MAIL(1)
#define ITEM_HARBOR_MAIL SECTION_MAIL(2)
#define ITEM_GLITTER_MAIL SECTION_MAIL(3)
#define ITEM_MECH_MAIL SECTION_MAIL(4)
#define ITEM_WOOD_MAIL SECTION_MAIL(5)
#define ITEM_WAVE_MAIL SECTION_MAIL(6)
#define ITEM_BEAD_MAIL SECTION_MAIL(7)
#define ITEM_SHADOW_MAIL SECTION_MAIL(8)
#define ITEM_TROPIC_MAIL SECTION_MAIL(9)
#define ITEM_DREAM_MAIL SECTION_MAIL(10)
#define ITEM_FAB_MAIL SECTION_MAIL(11)
#define ITEM_RETRO_MAIL SECTION_MAIL(12)

#define FIRST_MAIL_INDEX ITEM_ORANGE_MAIL

// Evolution Items
#define SECTION_EVOLUTION_ITEMS(x) (x + SECTION_MAIL(12))
#define ITEM_FIRE_STONE SECTION_EVOLUTION_ITEMS(1)
#define ITEM_WATER_STONE SECTION_EVOLUTION_ITEMS(2)
#define ITEM_THUNDER_STONE SECTION_EVOLUTION_ITEMS(3)
#define ITEM_THUNDERSTONE ITEM_THUNDER_STONE // Pre-Gen VI name
#define ITEM_LEAF_STONE SECTION_EVOLUTION_ITEMS(4)
#define ITEM_ICE_STONE SECTION_EVOLUTION_ITEMS(5)
#define ITEM_SUN_STONE SECTION_EVOLUTION_ITEMS(6)
#define ITEM_MOON_STONE SECTION_EVOLUTION_ITEMS(7)
#define ITEM_SHINY_STONE SECTION_EVOLUTION_ITEMS(8)
#define ITEM_DUSK_STONE SECTION_EVOLUTION_ITEMS(9)
#define ITEM_DAWN_STONE SECTION_EVOLUTION_ITEMS(10)
#define ITEM_SWEET_APPLE SECTION_EVOLUTION_ITEMS(11)
#define ITEM_TART_APPLE SECTION_EVOLUTION_ITEMS(12)
#define ITEM_CRACKED_POT SECTION_EVOLUTION_ITEMS(13)
#define ITEM_CHIPPED_POT SECTION_EVOLUTION_ITEMS(14)
#define ITEM_GALARICA_CUFF SECTION_EVOLUTION_ITEMS(15)
#define ITEM_GALARICA_WREATH SECTION_EVOLUTION_ITEMS(16)
#define ITEM_DRAGON_SCALE SECTION_EVOLUTION_ITEMS(17)
#define ITEM_UPGRADE SECTION_EVOLUTION_ITEMS(18)
#define ITEM_UP_GRADE ITEM_UPGRADE // Pre-Gen VIII name
#define ITEM_PROTECTOR SECTION_EVOLUTION_ITEMS(19)
#define ITEM_ELECTIRIZER SECTION_EVOLUTION_ITEMS(20)
#define ITEM_MAGMARIZER SECTION_EVOLUTION_ITEMS(21)
#define ITEM_DUBIOUS_DISC SECTION_EVOLUTION_ITEMS(22)
#define ITEM_REAPER_CLOTH SECTION_EVOLUTION_ITEMS(23)
#define ITEM_PRISM_SCALE SECTION_EVOLUTION_ITEMS(24)
#define ITEM_WHIPPED_DREAM SECTION_EVOLUTION_ITEMS(25)
#define ITEM_SACHET SECTION_EVOLUTION_ITEMS(26)
#define ITEM_OVAL_STONE SECTION_EVOLUTION_ITEMS(27)
#define ITEM_STRAWBERRY_SWEET SECTION_EVOLUTION_ITEMS(28)
#define ITEM_LOVE_SWEET SECTION_EVOLUTION_ITEMS(29)
#define ITEM_BERRY_SWEET SECTION_EVOLUTION_ITEMS(30)
#define ITEM_CLOVER_SWEET SECTION_EVOLUTION_ITEMS(31)
#define ITEM_FLOWER_SWEET SECTION_EVOLUTION_ITEMS(32)
#define ITEM_STAR_SWEET SECTION_EVOLUTION_ITEMS(33)
#define ITEM_RIBBON_SWEET SECTION_EVOLUTION_ITEMS(34)

#define ITEM_EVERSTONE SECTION_EVOLUTION_ITEMS(35)

// Nectars
#define SECTION_NECTARS(x) (x + SECTION_EVOLUTION_ITEMS(35))
#define ITEM_RED_NECTAR SECTION_NECTARS(1)
#define ITEM_YELLOW_NECTAR SECTION_NECTARS(2)
#define ITEM_PINK_NECTAR SECTION_NECTARS(3)
#define ITEM_PURPLE_NECTAR SECTION_NECTARS(4)

// Plates
#define SECTION_PLATES(x) (x + SECTION_NECTARS(4))
#define ITEM_FLAME_PLATE SECTION_PLATES(1)
#define ITEM_SPLASH_PLATE SECTION_PLATES(2)
#define ITEM_ZAP_PLATE SECTION_PLATES(3)
#define ITEM_MEADOW_PLATE SECTION_PLATES(4)
#define ITEM_ICICLE_PLATE SECTION_PLATES(5)
#define ITEM_FIST_PLATE SECTION_PLATES(6)
#define ITEM_TOXIC_PLATE SECTION_PLATES(7)
#define ITEM_EARTH_PLATE SECTION_PLATES(8)
#define ITEM_SKY_PLATE SECTION_PLATES(9)
#define ITEM_MIND_PLATE SECTION_PLATES(10)
#define ITEM_INSECT_PLATE SECTION_PLATES(11)
#define ITEM_STONE_PLATE SECTION_PLATES(12)
#define ITEM_SPOOKY_PLATE SECTION_PLATES(13)
#define ITEM_DRACO_PLATE SECTION_PLATES(14)
#define ITEM_DREAD_PLATE SECTION_PLATES(15)
#define ITEM_IRON_PLATE SECTION_PLATES(16)
#define ITEM_PIXIE_PLATE SECTION_PLATES(17)

// Drives
#define SECTION_DRIVES(x) (x + SECTION_PLATES(17))
#define ITEM_DOUSE_DRIVE SECTION_DRIVES(1)
#define ITEM_SHOCK_DRIVE SECTION_DRIVES(2)
#define ITEM_BURN_DRIVE SECTION_DRIVES(3)
#define ITEM_CHILL_DRIVE SECTION_DRIVES(4)

// Memories
#define SECTION_MEMORIES(x) (x + SECTION_DRIVES(4))
#define ITEM_FIRE_MEMORY SECTION_MEMORIES(1)
#define ITEM_WATER_MEMORY SECTION_MEMORIES(2)
#define ITEM_ELECTRIC_MEMORY SECTION_MEMORIES(3)
#define ITEM_GRASS_MEMORY SECTION_MEMORIES(4)
#define ITEM_ICE_MEMORY SECTION_MEMORIES(5)
#define ITEM_FIGHTING_MEMORY SECTION_MEMORIES(6)
#define ITEM_POISON_MEMORY SECTION_MEMORIES(7)
#define ITEM_GROUND_MEMORY SECTION_MEMORIES(8)
#define ITEM_FLYING_MEMORY SECTION_MEMORIES(9)
#define ITEM_PSYCHIC_MEMORY SECTION_MEMORIES(10)
#define ITEM_BUG_MEMORY SECTION_MEMORIES(11)
#define ITEM_ROCK_MEMORY SECTION_MEMORIES(12)
#define ITEM_GHOST_MEMORY SECTION_MEMORIES(13)
#define ITEM_DRAGON_MEMORY SECTION_MEMORIES(14)
#define ITEM_DARK_MEMORY SECTION_MEMORIES(15)
#define ITEM_STEEL_MEMORY SECTION_MEMORIES(16)
#define ITEM_FAIRY_MEMORY SECTION_MEMORIES(17)

#define ITEM_RUSTED_SWORD SECTION_MEMORIES(18)
#define ITEM_RUSTED_SHIELD SECTION_MEMORIES(19)

// Colored Orbs
#define SECTION_COLORED_ORBS(x) (x + SECTION_MEMORIES(19))
#define ITEM_RED_ORB SECTION_COLORED_ORBS(1)
#define ITEM_BLUE_ORB SECTION_COLORED_ORBS(2)

// Mega Stones
#define SECTION_MEGA_STONES(x) (x + SECTION_COLORED_ORBS(2))
#define ITEM_VENUSAURITE SECTION_MEGA_STONES(1)
#define ITEM_CHARIZARDITE_X SECTION_MEGA_STONES(2)
#define ITEM_CHARIZARDITE_Y SECTION_MEGA_STONES(3)
#define ITEM_BLASTOISINITE SECTION_MEGA_STONES(4)
#define ITEM_BEEDRILLITE SECTION_MEGA_STONES(5)
#define ITEM_PIDGEOTITE SECTION_MEGA_STONES(6)
#define ITEM_ALAKAZITE SECTION_MEGA_STONES(7)
#define ITEM_SLOWBRONITE SECTION_MEGA_STONES(8)
#define ITEM_GENGARITE SECTION_MEGA_STONES(9)
#define ITEM_KANGASKHANITE SECTION_MEGA_STONES(10)
#define ITEM_PINSIRITE SECTION_MEGA_STONES(11)
#define ITEM_GYARADOSITE SECTION_MEGA_STONES(12)
#define ITEM_AERODACTYLITE SECTION_MEGA_STONES(13)
#define ITEM_MEWTWONITE_X SECTION_MEGA_STONES(14)
#define ITEM_MEWTWONITE_Y SECTION_MEGA_STONES(15)
#define ITEM_AMPHAROSITE SECTION_MEGA_STONES(16)
#define ITEM_STEELIXITE SECTION_MEGA_STONES(17)
#define ITEM_SCIZORITE SECTION_MEGA_STONES(18)
#define ITEM_HERACRONITE SECTION_MEGA_STONES(19)
#define ITEM_HOUNDOOMINITE SECTION_MEGA_STONES(20)
#define ITEM_TYRANITARITE SECTION_MEGA_STONES(21)
#define ITEM_SCEPTILITE SECTION_MEGA_STONES(22)
#define ITEM_BLAZIKENITE SECTION_MEGA_STONES(23)
#define ITEM_SWAMPERTITE SECTION_MEGA_STONES(24)
#define ITEM_GARDEVOIRITE SECTION_MEGA_STONES(25)
#define ITEM_SABLENITE SECTION_MEGA_STONES(26)
#define ITEM_MAWILITE SECTION_MEGA_STONES(27)
#define ITEM_AGGRONITE SECTION_MEGA_STONES(28)
#define ITEM_MEDICHAMITE SECTION_MEGA_STONES(29)
#define ITEM_MANECTITE SECTION_MEGA_STONES(30)
#define ITEM_SHARPEDONITE SECTION_MEGA_STONES(31)
#define ITEM_CAMERUPTITE SECTION_MEGA_STONES(32)
#define ITEM_ALTARIANITE SECTION_MEGA_STONES(33)
#define ITEM_BANETTITE SECTION_MEGA_STONES(34)
#define ITEM_ABSOLITE SECTION_MEGA_STONES(35)
#define ITEM_GLALITITE SECTION_MEGA_STONES(36)
#define ITEM_SALAMENCITE SECTION_MEGA_STONES(37)
#define ITEM_METAGROSSITE SECTION_MEGA_STONES(38)
#define ITEM_LATIASITE SECTION_MEGA_STONES(39)
#define ITEM_LATIOSITE SECTION_MEGA_STONES(40)
#define ITEM_LOPUNNITE SECTION_MEGA_STONES(41)
#define ITEM_GARCHOMPITE SECTION_MEGA_STONES(42)
#define ITEM_LUCARIONITE SECTION_MEGA_STONES(43)
#define ITEM_ABOMASITE SECTION_MEGA_STONES(44)
#define ITEM_GALLADITE SECTION_MEGA_STONES(45)
#define ITEM_AUDINITE SECTION_MEGA_STONES(46)
#define ITEM_DIANCITE SECTION_MEGA_STONES(47)

// Gems
#define SECTION_GEMS(x) (x + SECTION_MEGA_STONES(47))
#define ITEM_NORMAL_GEM SECTION_GEMS(1)
#define ITEM_FIRE_GEM SECTION_GEMS(2)
#define ITEM_WATER_GEM SECTION_GEMS(3)
#define ITEM_ELECTRIC_GEM SECTION_GEMS(4)
#define ITEM_GRASS_GEM SECTION_GEMS(5)
#define ITEM_ICE_GEM SECTION_GEMS(6)
#define ITEM_FIGHTING_GEM SECTION_GEMS(7)
#define ITEM_POISON_GEM SECTION_GEMS(8)
#define ITEM_GROUND_GEM SECTION_GEMS(9)
#define ITEM_FLYING_GEM SECTION_GEMS(10)
#define ITEM_PSYCHIC_GEM SECTION_GEMS(11)
#define ITEM_BUG_GEM SECTION_GEMS(12)
#define ITEM_ROCK_GEM SECTION_GEMS(13)
#define ITEM_GHOST_GEM SECTION_GEMS(14)
#define ITEM_DRAGON_GEM SECTION_GEMS(15)
#define ITEM_DARK_GEM SECTION_GEMS(16)
#define ITEM_STEEL_GEM SECTION_GEMS(17)
#define ITEM_FAIRY_GEM SECTION_GEMS(18)

// Z-Crystals
#define SECTION_Z_CRYSTALS(x) (x + SECTION_GEMS(18))
#define ITEM_NORMALIUM_Z SECTION_Z_CRYSTALS(1)
#define ITEM_FIRIUM_Z SECTION_Z_CRYSTALS(2)
#define ITEM_WATERIUM_Z SECTION_Z_CRYSTALS(3)
#define ITEM_ELECTRIUM_Z SECTION_Z_CRYSTALS(4)
#define ITEM_GRASSIUM_Z SECTION_Z_CRYSTALS(5)
#define ITEM_ICIUM_Z SECTION_Z_CRYSTALS(6)
#define ITEM_FIGHTINIUM_Z SECTION_Z_CRYSTALS(7)
#define ITEM_POISONIUM_Z SECTION_Z_CRYSTALS(8)
#define ITEM_GROUNDIUM_Z SECTION_Z_CRYSTALS(9)
#define ITEM_FLYINIUM_Z SECTION_Z_CRYSTALS(10)
#define ITEM_PSYCHIUM_Z SECTION_Z_CRYSTALS(11)
#define ITEM_BUGINIUM_Z SECTION_Z_CRYSTALS(12)
#define ITEM_ROCKIUM_Z SECTION_Z_CRYSTALS(13)
#define ITEM_GHOSTIUM_Z SECTION_Z_CRYSTALS(14)
#define ITEM_DRAGONIUM_Z SECTION_Z_CRYSTALS(15)
#define ITEM_DARKINIUM_Z SECTION_Z_CRYSTALS(16)
#define ITEM_STEELIUM_Z SECTION_Z_CRYSTALS(17)
#define ITEM_FAIRIUM_Z SECTION_Z_CRYSTALS(18)
#define ITEM_PIKANIUM_Z SECTION_Z_CRYSTALS(19)
#define ITEM_EEVIUM_Z SECTION_Z_CRYSTALS(20)
#define ITEM_SNORLIUM_Z SECTION_Z_CRYSTALS(21)
#define ITEM_MEWNIUM_Z SECTION_Z_CRYSTALS(22)
#define ITEM_DECIDIUM_Z SECTION_Z_CRYSTALS(23)
#define ITEM_INCINIUM_Z SECTION_Z_CRYSTALS(24)
#define ITEM_PRIMARIUM_Z SECTION_Z_CRYSTALS(25)
#define ITEM_LYCANIUM_Z SECTION_Z_CRYSTALS(26)
#define ITEM_MIMIKIUM_Z SECTION_Z_CRYSTALS(27)
#define ITEM_KOMMONIUM_Z SECTION_Z_CRYSTALS(28)
#define ITEM_TAPUNIUM_Z SECTION_Z_CRYSTALS(29)
#define ITEM_SOLGANIUM_Z SECTION_Z_CRYSTALS(30)
#define ITEM_LUNALIUM_Z SECTION_Z_CRYSTALS(31)
#define ITEM_MARSHADIUM_Z SECTION_Z_CRYSTALS(32)
#define ITEM_ALORAICHIUM_Z SECTION_Z_CRYSTALS(33)
#define ITEM_PIKASHUNIUM_Z SECTION_Z_CRYSTALS(34)
#define ITEM_ULTRANECROZIUM_Z SECTION_Z_CRYSTALS(35)

// Species-specific Held Items
#define SECTION_SPECIES_SPECIFIC_HELD_ITEMS(x) (x + SECTION_Z_CRYSTALS(35))
#define ITEM_LIGHT_BALL SECTION_SPECIES_SPECIFIC_HELD_ITEMS(1)
#define ITEM_LEEK SECTION_SPECIES_SPECIFIC_HELD_ITEMS(2)
#define ITEM_STICK ITEM_LEEK // Pre-Gen VIII name
#define ITEM_THICK_CLUB SECTION_SPECIES_SPECIFIC_HELD_ITEMS(3)
#define ITEM_LUCKY_PUNCH SECTION_SPECIES_SPECIFIC_HELD_ITEMS(4)
#define ITEM_METAL_POWDER SECTION_SPECIES_SPECIFIC_HELD_ITEMS(5)
#define ITEM_QUICK_POWDER SECTION_SPECIES_SPECIFIC_HELD_ITEMS(6)
#define ITEM_DEEP_SEA_SCALE SECTION_SPECIES_SPECIFIC_HELD_ITEMS(7)
#define ITEM_DEEPSEASCALE ITEM_DEEP_SEA_SCALE // Pre-Gen VI name
#define ITEM_DEEP_SEA_TOOTH SECTION_SPECIES_SPECIFIC_HELD_ITEMS(8)
#define ITEM_DEEPSEATOOTH ITEM_DEEP_SEA_TOOTH // Pre-Gen VI name
#define ITEM_SOUL_DEW SECTION_SPECIES_SPECIFIC_HELD_ITEMS(9)
#define ITEM_ADAMANT_ORB SECTION_SPECIES_SPECIFIC_HELD_ITEMS(10)
#define ITEM_LUSTROUS_ORB SECTION_SPECIES_SPECIFIC_HELD_ITEMS(11)
#define ITEM_GRISEOUS_ORB SECTION_SPECIES_SPECIFIC_HELD_ITEMS(12)

// Incenses
#define SECTION_INCENSES(x) (x + SECTION_SPECIES_SPECIFIC_HELD_ITEMS(12))
#define ITEM_SEA_INCENSE SECTION_INCENSES(1)
#define ITEM_LAX_INCENSE SECTION_INCENSES(2)
#define ITEM_ODD_INCENSE SECTION_INCENSES(3)
#define ITEM_ROCK_INCENSE SECTION_INCENSES(4)
#define ITEM_FULL_INCENSE SECTION_INCENSES(5)
#define ITEM_WAVE_INCENSE SECTION_INCENSES(6)
#define ITEM_ROSE_INCENSE SECTION_INCENSES(7)
#define ITEM_LUCK_INCENSE SECTION_INCENSES(8)
#define ITEM_PURE_INCENSE SECTION_INCENSES(9)

// Contest Scarves
#define SECTION_CONTEST_SCARVES(x) (x + SECTION_INCENSES(9))
#define ITEM_RED_SCARF SECTION_CONTEST_SCARVES(1)
#define ITEM_BLUE_SCARF SECTION_CONTEST_SCARVES(2)
#define ITEM_PINK_SCARF SECTION_CONTEST_SCARVES(3)
#define ITEM_GREEN_SCARF SECTION_CONTEST_SCARVES(4)
#define ITEM_YELLOW_SCARF SECTION_CONTEST_SCARVES(5)

// EV Gain Modifiers
#define SECTION_EV_GAIN_MODIFIERS(x) (x + SECTION_CONTEST_SCARVES(5))
#define ITEM_MACHO_BRACE SECTION_EV_GAIN_MODIFIERS(1)
#define ITEM_POWER_WEIGHT SECTION_EV_GAIN_MODIFIERS(2)
#define ITEM_POWER_BRACER SECTION_EV_GAIN_MODIFIERS(3)
#define ITEM_POWER_BELT SECTION_EV_GAIN_MODIFIERS(4)
#define ITEM_POWER_LENS SECTION_EV_GAIN_MODIFIERS(5)
#define ITEM_POWER_BAND SECTION_EV_GAIN_MODIFIERS(6)
#define ITEM_POWER_ANKLET SECTION_EV_GAIN_MODIFIERS(7)

// Type-boosting Held Items
#define SECTION_TYPE_BOOSTING_HELD_ITEMS(x) (x + SECTION_EV_GAIN_MODIFIERS(7))
#define ITEM_SILK_SCARF SECTION_TYPE_BOOSTING_HELD_ITEMS(1)
#define ITEM_CHARCOAL SECTION_TYPE_BOOSTING_HELD_ITEMS(2)
#define ITEM_MYSTIC_WATER SECTION_TYPE_BOOSTING_HELD_ITEMS(3)
#define ITEM_MAGNET SECTION_TYPE_BOOSTING_HELD_ITEMS(4)
#define ITEM_MIRACLE_SEED SECTION_TYPE_BOOSTING_HELD_ITEMS(5)
#define ITEM_NEVER_MELT_ICE SECTION_TYPE_BOOSTING_HELD_ITEMS(6)
#define ITEM_NEVERMELTICE ITEM_NEVER_MELT_ICE // Pre-Gen VI name
#define ITEM_BLACK_BELT SECTION_TYPE_BOOSTING_HELD_ITEMS(7)
#define ITEM_BLACKBELT ITEM_BLACK_BELT // Gen II name
#define ITEM_POISON_BARB SECTION_TYPE_BOOSTING_HELD_ITEMS(8)
#define ITEM_SOFT_SAND SECTION_TYPE_BOOSTING_HELD_ITEMS(9)
#define ITEM_SHARP_BEAK SECTION_TYPE_BOOSTING_HELD_ITEMS(10)
#define ITEM_TWISTED_SPOON SECTION_TYPE_BOOSTING_HELD_ITEMS(11)
#define ITEM_TWISTEDSPOON ITEM_TWISTED_SPOON // Pre-Gen VI name
#define ITEM_SILVER_POWDER SECTION_TYPE_BOOSTING_HELD_ITEMS(12)
#define ITEM_SILVERPOWDER ITEM_SILVER_POWDER // Pre-Gen VI name
#define ITEM_HARD_STONE SECTION_TYPE_BOOSTING_HELD_ITEMS(13)
#define ITEM_SPELL_TAG SECTION_TYPE_BOOSTING_HELD_ITEMS(14)
#define ITEM_DRAGON_FANG SECTION_TYPE_BOOSTING_HELD_ITEMS(15)
#define ITEM_BLACK_GLASSES SECTION_TYPE_BOOSTING_HELD_ITEMS(16)
#define ITEM_BLACKGLASSES ITEM_BLACK_GLASSES // Pre-Gen VI name
#define ITEM_METAL_COAT SECTION_TYPE_BOOSTING_HELD_ITEMS(17)

// Choice Items
#define SECTION_CHOICE_ITEMS(x) (x + SECTION_TYPE_BOOSTING_HELD_ITEMS(17))
#define ITEM_CHOICE_BAND SECTION_CHOICE_ITEMS(1)
#define ITEM_CHOICE_SPECS SECTION_CHOICE_ITEMS(2)
#define ITEM_CHOICE_SCARF SECTION_CHOICE_ITEMS(3)

// Status Orbs
#define SECTION_STATUS_ORBS(x) (x + SECTION_CHOICE_ITEMS(3))
#define ITEM_FLAME_ORB SECTION_STATUS_ORBS(1)
#define ITEM_TOXIC_ORB SECTION_STATUS_ORBS(2)

// Weather Rocks
#define SECTION_WEATHER_ROCKS(x) (x + SECTION_STATUS_ORBS(2))
#define ITEM_DAMP_ROCK SECTION_WEATHER_ROCKS(1)
#define ITEM_HEAT_ROCK SECTION_WEATHER_ROCKS(2)
#define ITEM_SMOOTH_ROCK SECTION_WEATHER_ROCKS(3)
#define ITEM_ICY_ROCK SECTION_WEATHER_ROCKS(4)

// Terrain Seeds
#define SECTION_TERRAIN_SEEDS(x) (x + SECTION_WEATHER_ROCKS(4))
#define ITEM_ELECTRIC_SEED SECTION_TERRAIN_SEEDS(1)
#define ITEM_PSYCHIC_SEED SECTION_TERRAIN_SEEDS(2)
#define ITEM_MISTY_SEED SECTION_TERRAIN_SEEDS(3)
#define ITEM_GRASSY_SEED SECTION_TERRAIN_SEEDS(4)

// Type-activated Stat Modifiers
#define SECTION_TYPE_ACTIVATED_STAT_MODIFIERS(x) (x + SECTION_TERRAIN_SEEDS(4))
#define ITEM_ABSORB_BULB SECTION_TYPE_ACTIVATED_STAT_MODIFIERS(1)
#define ITEM_CELL_BATTERY SECTION_TYPE_ACTIVATED_STAT_MODIFIERS(2)
#define ITEM_LUMINOUS_MOSS SECTION_TYPE_ACTIVATED_STAT_MODIFIERS(3)
#define ITEM_SNOWBALL SECTION_TYPE_ACTIVATED_STAT_MODIFIERS(4)

// Misc. Held Items
#define SECTION_MISC_HELD_ITEMS(x) (x + SECTION_TYPE_ACTIVATED_STAT_MODIFIERS(4))
#define ITEM_BRIGHT_POWDER SECTION_MISC_HELD_ITEMS(1)
#define ITEM_BRIGHTPOWDER ITEM_BRIGHT_POWDER // Pre-Gen VI name
#define ITEM_WHITE_HERB SECTION_MISC_HELD_ITEMS(2)
#define ITEM_EXP_SHARE SECTION_MISC_HELD_ITEMS(3)
#define ITEM_EXP_ALL ITEM_EXP_SHARE // Gen I name
#define ITEM_QUICK_CLAW SECTION_MISC_HELD_ITEMS(4)
#define ITEM_SOOTHE_BELL SECTION_MISC_HELD_ITEMS(5)
#define ITEM_MENTAL_HERB SECTION_MISC_HELD_ITEMS(6)
#define ITEM_KINGS_ROCK SECTION_MISC_HELD_ITEMS(7)
#define ITEM_AMULET_COIN SECTION_MISC_HELD_ITEMS(8)
#define ITEM_CLEANSE_TAG SECTION_MISC_HELD_ITEMS(9)
#define ITEM_SMOKE_BALL SECTION_MISC_HELD_ITEMS(10)
#define ITEM_FOCUS_BAND SECTION_MISC_HELD_ITEMS(11)
#define ITEM_LUCKY_EGG SECTION_MISC_HELD_ITEMS(12)
#define ITEM_SCOPE_LENS SECTION_MISC_HELD_ITEMS(13)
#define ITEM_LEFTOVERS SECTION_MISC_HELD_ITEMS(14)
#define ITEM_SHELL_BELL SECTION_MISC_HELD_ITEMS(15)
#define ITEM_WIDE_LENS SECTION_MISC_HELD_ITEMS(16)
#define ITEM_MUSCLE_BAND SECTION_MISC_HELD_ITEMS(17)
#define ITEM_WISE_GLASSES SECTION_MISC_HELD_ITEMS(18)
#define ITEM_EXPERT_BELT SECTION_MISC_HELD_ITEMS(19)
#define ITEM_LIGHT_CLAY SECTION_MISC_HELD_ITEMS(20)
#define ITEM_LIFE_ORB SECTION_MISC_HELD_ITEMS(21)
#define ITEM_POWER_HERB SECTION_MISC_HELD_ITEMS(22)
#define ITEM_FOCUS_SASH SECTION_MISC_HELD_ITEMS(23)
#define ITEM_ZOOM_LENS SECTION_MISC_HELD_ITEMS(24)
#define ITEM_METRONOME SECTION_MISC_HELD_ITEMS(25)
#define ITEM_IRON_BALL SECTION_MISC_HELD_ITEMS(26)
#define ITEM_LAGGING_TAIL SECTION_MISC_HELD_ITEMS(27)
#define ITEM_DESTINY_KNOT SECTION_MISC_HELD_ITEMS(28)
#define ITEM_BLACK_SLUDGE SECTION_MISC_HELD_ITEMS(29)
#define ITEM_GRIP_CLAW SECTION_MISC_HELD_ITEMS(30)
#define ITEM_STICKY_BARB SECTION_MISC_HELD_ITEMS(31)
#define ITEM_SHED_SHELL SECTION_MISC_HELD_ITEMS(32)
#define ITEM_BIG_ROOT SECTION_MISC_HELD_ITEMS(33)
#define ITEM_RAZOR_CLAW SECTION_MISC_HELD_ITEMS(34)
#define ITEM_RAZOR_FANG SECTION_MISC_HELD_ITEMS(35)
#define ITEM_EVIOLITE SECTION_MISC_HELD_ITEMS(36)
#define ITEM_FLOAT_STONE SECTION_MISC_HELD_ITEMS(37)
#define ITEM_ROCKY_HELMET SECTION_MISC_HELD_ITEMS(38)
#define ITEM_AIR_BALLOON SECTION_MISC_HELD_ITEMS(39)
#define ITEM_RED_CARD SECTION_MISC_HELD_ITEMS(40)
#define ITEM_RING_TARGET SECTION_MISC_HELD_ITEMS(41)
#define ITEM_BINDING_BAND SECTION_MISC_HELD_ITEMS(42)
#define ITEM_EJECT_BUTTON SECTION_MISC_HELD_ITEMS(43)
#define ITEM_WEAKNESS_POLICY SECTION_MISC_HELD_ITEMS(44)
#define ITEM_ASSAULT_VEST SECTION_MISC_HELD_ITEMS(45)
#define ITEM_SAFETY_GOGGLES SECTION_MISC_HELD_ITEMS(46)
#define ITEM_ADRENALINE_ORB SECTION_MISC_HELD_ITEMS(47)
#define ITEM_TERRAIN_EXTENDER SECTION_MISC_HELD_ITEMS(48)
#define ITEM_PROTECTIVE_PADS SECTION_MISC_HELD_ITEMS(49)
#define ITEM_THROAT_SPRAY SECTION_MISC_HELD_ITEMS(50)
#define ITEM_EJECT_PACK SECTION_MISC_HELD_ITEMS(51)
#define ITEM_HEAVY_DUTY_BOOTS SECTION_MISC_HELD_ITEMS(52)
#define ITEM_BLUNDER_POLICY SECTION_MISC_HELD_ITEMS(53)
#define ITEM_ROOM_SERVICE SECTION_MISC_HELD_ITEMS(54)
#define ITEM_UTILITY_UMBRELLA SECTION_MISC_HELD_ITEMS(55)

// Berries
#if B_CONFUSE_BERRIES_HEAL >= GEN_8
    #define CONFUSE_BERRY_HEAL_FRACTION 3
#elif B_CONFUSE_BERRIES_HEAL == GEN_7
    #define CONFUSE_BERRY_HEAL_FRACTION 2
#else
    #define CONFUSE_BERRY_HEAL_FRACTION 8
#endif

#define CONFUSE_BERRY_HP_FRACTION ((B_CONFUSE_BERRIES_HEAL >= GEN_7) ? 4 : 2)

#define SECTION_BERRIES(x) (x + SECTION_MISC_HELD_ITEMS(55))
#define ITEM_CHERI_BERRY SECTION_BERRIES(1)
#define ITEM_CHESTO_BERRY SECTION_BERRIES(2)
#define ITEM_PECHA_BERRY SECTION_BERRIES(3)
#define ITEM_RAWST_BERRY SECTION_BERRIES(4)
#define ITEM_ASPEAR_BERRY SECTION_BERRIES(5)
#define ITEM_LEPPA_BERRY SECTION_BERRIES(6)
#define ITEM_ORAN_BERRY SECTION_BERRIES(7)
#define ITEM_PERSIM_BERRY SECTION_BERRIES(8)
#define ITEM_LUM_BERRY SECTION_BERRIES(9)
#define ITEM_SITRUS_BERRY SECTION_BERRIES(10)
#define ITEM_FIGY_BERRY SECTION_BERRIES(11)
#define ITEM_WIKI_BERRY SECTION_BERRIES(12)
#define ITEM_MAGO_BERRY SECTION_BERRIES(13)
#define ITEM_AGUAV_BERRY SECTION_BERRIES(14)
#define ITEM_IAPAPA_BERRY SECTION_BERRIES(15)
#define ITEM_RAZZ_BERRY SECTION_BERRIES(16)
#define ITEM_BLUK_BERRY SECTION_BERRIES(17)
#define ITEM_NANAB_BERRY SECTION_BERRIES(18)
#define ITEM_WEPEAR_BERRY SECTION_BERRIES(19)
#define ITEM_PINAP_BERRY SECTION_BERRIES(20)
#define ITEM_POMEG_BERRY SECTION_BERRIES(21)
#define ITEM_KELPSY_BERRY SECTION_BERRIES(22)
#define ITEM_QUALOT_BERRY SECTION_BERRIES(23)
#define ITEM_HONDEW_BERRY SECTION_BERRIES(24)
#define ITEM_GREPA_BERRY SECTION_BERRIES(25)
#define ITEM_TAMATO_BERRY SECTION_BERRIES(26)
#define ITEM_CORNN_BERRY SECTION_BERRIES(27)
#define ITEM_MAGOST_BERRY SECTION_BERRIES(28)
#define ITEM_RABUTA_BERRY SECTION_BERRIES(29)
#define ITEM_NOMEL_BERRY SECTION_BERRIES(30)
#define ITEM_SPELON_BERRY SECTION_BERRIES(31)
#define ITEM_PAMTRE_BERRY SECTION_BERRIES(32)
#define ITEM_WATMEL_BERRY SECTION_BERRIES(33)
#define ITEM_DURIN_BERRY SECTION_BERRIES(34)
#define ITEM_BELUE_BERRY SECTION_BERRIES(35)
#define ITEM_CHILAN_BERRY SECTION_BERRIES(36)
#define ITEM_OCCA_BERRY SECTION_BERRIES(37)
#define ITEM_PASSHO_BERRY SECTION_BERRIES(38)
#define ITEM_WACAN_BERRY SECTION_BERRIES(39)
#define ITEM_RINDO_BERRY SECTION_BERRIES(40)
#define ITEM_YACHE_BERRY SECTION_BERRIES(41)
#define ITEM_CHOPLE_BERRY SECTION_BERRIES(42)
#define ITEM_KEBIA_BERRY SECTION_BERRIES(43)
#define ITEM_SHUCA_BERRY SECTION_BERRIES(44)
#define ITEM_COBA_BERRY SECTION_BERRIES(45)
#define ITEM_PAYAPA_BERRY SECTION_BERRIES(46)
#define ITEM_TANGA_BERRY SECTION_BERRIES(47)
#define ITEM_CHARTI_BERRY SECTION_BERRIES(48)
#define ITEM_KASIB_BERRY SECTION_BERRIES(49)
#define ITEM_HABAN_BERRY SECTION_BERRIES(50)
#define ITEM_COLBUR_BERRY SECTION_BERRIES(51)
#define ITEM_BABIRI_BERRY SECTION_BERRIES(52)
#define ITEM_ROSELI_BERRY SECTION_BERRIES(53)
#define ITEM_LIECHI_BERRY SECTION_BERRIES(54)
#define ITEM_GANLON_BERRY SECTION_BERRIES(55)
#define ITEM_SALAC_BERRY SECTION_BERRIES(56)
#define ITEM_PETAYA_BERRY SECTION_BERRIES(57)
#define ITEM_APICOT_BERRY SECTION_BERRIES(58)
#define ITEM_LANSAT_BERRY SECTION_BERRIES(59)
#define ITEM_STARF_BERRY SECTION_BERRIES(60)
#define ITEM_ENIGMA_BERRY SECTION_BERRIES(61)
#define ITEM_MICLE_BERRY SECTION_BERRIES(62)
#define ITEM_CUSTAP_BERRY SECTION_BERRIES(63)
#define ITEM_JABOCA_BERRY SECTION_BERRIES(64)
#define ITEM_ROWAP_BERRY SECTION_BERRIES(65)
#define ITEM_KEE_BERRY SECTION_BERRIES(66)
#define ITEM_MARANGA_BERRY SECTION_BERRIES(67)
#define ITEM_ENIGMA_BERRY_E_READER SECTION_BERRIES(68)

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX  ITEM_ENIGMA_BERRY_E_READER

// TMs/HMs
#define SECTION_TMS_HMS(x) (x + SECTION_BERRIES(68))
#define ITEM_TM01 SECTION_TMS_HMS(1)
#define ITEM_TM02 SECTION_TMS_HMS(2)
#define ITEM_TM03 SECTION_TMS_HMS(3)
#define ITEM_TM04 SECTION_TMS_HMS(4)
#define ITEM_TM05 SECTION_TMS_HMS(5)
#define ITEM_TM06 SECTION_TMS_HMS(6)
#define ITEM_TM07 SECTION_TMS_HMS(7)
#define ITEM_TM08 SECTION_TMS_HMS(8)
#define ITEM_TM09 SECTION_TMS_HMS(9)
#define ITEM_TM10 SECTION_TMS_HMS(10)
#define ITEM_TM11 SECTION_TMS_HMS(11)
#define ITEM_TM12 SECTION_TMS_HMS(12)
#define ITEM_TM13 SECTION_TMS_HMS(13)
#define ITEM_TM14 SECTION_TMS_HMS(14)
#define ITEM_TM15 SECTION_TMS_HMS(15)
#define ITEM_TM16 SECTION_TMS_HMS(16)
#define ITEM_TM17 SECTION_TMS_HMS(17)
#define ITEM_TM18 SECTION_TMS_HMS(18)
#define ITEM_TM19 SECTION_TMS_HMS(19)
#define ITEM_TM20 SECTION_TMS_HMS(20)
#define ITEM_TM21 SECTION_TMS_HMS(21)
#define ITEM_TM22 SECTION_TMS_HMS(22)
#define ITEM_TM23 SECTION_TMS_HMS(23)
#define ITEM_TM24 SECTION_TMS_HMS(24)
#define ITEM_TM25 SECTION_TMS_HMS(25)
#define ITEM_TM26 SECTION_TMS_HMS(26)
#define ITEM_TM27 SECTION_TMS_HMS(27)
#define ITEM_TM28 SECTION_TMS_HMS(28)
#define ITEM_TM29 SECTION_TMS_HMS(29)
#define ITEM_TM30 SECTION_TMS_HMS(30)
#define ITEM_TM31 SECTION_TMS_HMS(31)
#define ITEM_TM32 SECTION_TMS_HMS(32)
#define ITEM_TM33 SECTION_TMS_HMS(33)
#define ITEM_TM34 SECTION_TMS_HMS(34)
#define ITEM_TM35 SECTION_TMS_HMS(35)
#define ITEM_TM36 SECTION_TMS_HMS(36)
#define ITEM_TM37 SECTION_TMS_HMS(37)
#define ITEM_TM38 SECTION_TMS_HMS(38)
#define ITEM_TM39 SECTION_TMS_HMS(39)
#define ITEM_TM40 SECTION_TMS_HMS(40)
#define ITEM_TM41 SECTION_TMS_HMS(41)
#define ITEM_TM42 SECTION_TMS_HMS(42)
#define ITEM_TM43 SECTION_TMS_HMS(43)
#define ITEM_TM44 SECTION_TMS_HMS(44)
#define ITEM_TM45 SECTION_TMS_HMS(45)
#define ITEM_TM46 SECTION_TMS_HMS(46)
#define ITEM_TM47 SECTION_TMS_HMS(47)
#define ITEM_TM48 SECTION_TMS_HMS(48)
#define ITEM_TM49 SECTION_TMS_HMS(49)
#define ITEM_TM50 SECTION_TMS_HMS(50)
#define ITEM_TM51 SECTION_TMS_HMS(51)
#define ITEM_TM52 SECTION_TMS_HMS(52)
#define ITEM_TM53 SECTION_TMS_HMS(53)
#define ITEM_TM54 SECTION_TMS_HMS(54)
#define ITEM_TM55 SECTION_TMS_HMS(55)
#define ITEM_TM56 SECTION_TMS_HMS(56)
#define ITEM_TM57 SECTION_TMS_HMS(57)
#define ITEM_TM58 SECTION_TMS_HMS(58)
#define ITEM_TM59 SECTION_TMS_HMS(59)
#define ITEM_TM60 SECTION_TMS_HMS(60)
#define ITEM_TM61 SECTION_TMS_HMS(61)
#define ITEM_TM62 SECTION_TMS_HMS(62)
#define ITEM_TM63 SECTION_TMS_HMS(63)
#define ITEM_TM64 SECTION_TMS_HMS(64)
#define ITEM_TM65 SECTION_TMS_HMS(65)
#define ITEM_TM66 SECTION_TMS_HMS(66)
#define ITEM_TM67 SECTION_TMS_HMS(67)
#define ITEM_TM68 SECTION_TMS_HMS(68)
#define ITEM_TM69 SECTION_TMS_HMS(69)
#define ITEM_TM70 SECTION_TMS_HMS(70)
#define ITEM_TM71 SECTION_TMS_HMS(71)
#define ITEM_TM72 SECTION_TMS_HMS(72)
#define ITEM_TM73 SECTION_TMS_HMS(73)
#define ITEM_TM74 SECTION_TMS_HMS(74)
#define ITEM_TM75 SECTION_TMS_HMS(75)
#define ITEM_TM76 SECTION_TMS_HMS(76)
#define ITEM_TM77 SECTION_TMS_HMS(77)
#define ITEM_TM78 SECTION_TMS_HMS(78)
#define ITEM_TM79 SECTION_TMS_HMS(79)
#define ITEM_TM80 SECTION_TMS_HMS(80)
#define ITEM_TM81 SECTION_TMS_HMS(81)
#define ITEM_TM82 SECTION_TMS_HMS(82)
#define ITEM_TM83 SECTION_TMS_HMS(83)
#define ITEM_TM84 SECTION_TMS_HMS(84)
#define ITEM_TM85 SECTION_TMS_HMS(85)
#define ITEM_TM86 SECTION_TMS_HMS(86)
#define ITEM_TM87 SECTION_TMS_HMS(87)
#define ITEM_TM88 SECTION_TMS_HMS(88)
#define ITEM_TM89 SECTION_TMS_HMS(89)
#define ITEM_TM90 SECTION_TMS_HMS(90)
#define ITEM_TM91 SECTION_TMS_HMS(91)
#define ITEM_TM92 SECTION_TMS_HMS(92)
#define ITEM_TM93 SECTION_TMS_HMS(93)
#define ITEM_TM94 SECTION_TMS_HMS(94)
#define ITEM_TM95 SECTION_TMS_HMS(95)
#define ITEM_TM96 SECTION_TMS_HMS(96)
#define ITEM_TM97 SECTION_TMS_HMS(97)
#define ITEM_TM98 SECTION_TMS_HMS(98)
#define ITEM_TM99 SECTION_TMS_HMS(99)
#define ITEM_TM100 SECTION_TMS_HMS(100)

#define ITEM_HM01 SECTION_TMS_HMS(101)
#define ITEM_HM02 SECTION_TMS_HMS(102)
#define ITEM_HM03 SECTION_TMS_HMS(103)
#define ITEM_HM04 SECTION_TMS_HMS(104)
#define ITEM_HM05 SECTION_TMS_HMS(105)
#define ITEM_HM06 SECTION_TMS_HMS(106)
#define ITEM_HM07 SECTION_TMS_HMS(107)
#define ITEM_HM08 SECTION_TMS_HMS(108)
#define ITEM_HM09 SECTION_TMS_HMS(109)

#define SECTION_TMS_HMS_END SECTION_TMS_HMS(109)

// Charms
#define SECTION_CHARMS(x) (x + SECTION_TMS_HMS(109))
#define ITEM_OVAL_CHARM SECTION_CHARMS(1)
#define ITEM_SHINY_CHARM SECTION_CHARMS(2)
#define ITEM_CATCHING_CHARM SECTION_CHARMS(3)
#define ITEM_EXP_CHARM SECTION_CHARMS(4)

// Form-changing Key Items
#define SECTION_FORM_CHANGING_KEY_ITEMS(x) (x + SECTION_CHARMS(4))
#define ITEM_ROTOM_CATALOG SECTION_FORM_CHANGING_KEY_ITEMS(1)
#define ITEM_GRACIDEA SECTION_FORM_CHANGING_KEY_ITEMS(2)
#define ITEM_REVEAL_GLASS SECTION_FORM_CHANGING_KEY_ITEMS(3)
#define ITEM_DNA_SPLICERS SECTION_FORM_CHANGING_KEY_ITEMS(4)
#define ITEM_ZYGARDE_CUBE SECTION_FORM_CHANGING_KEY_ITEMS(5)
#define ITEM_PRISON_BOTTLE SECTION_FORM_CHANGING_KEY_ITEMS(6)
#define ITEM_N_SOLARIZER SECTION_FORM_CHANGING_KEY_ITEMS(7)
#define ITEM_N_LUNARIZER SECTION_FORM_CHANGING_KEY_ITEMS(8)
#define ITEM_REINS_OF_UNITY SECTION_FORM_CHANGING_KEY_ITEMS(9)

// Battle Mechanic Key Items
#define SECTION_BATTLE_MECHANIC_KEY_ITEMS(x) (x + SECTION_FORM_CHANGING_KEY_ITEMS(9))
#define ITEM_MEGA_RING SECTION_BATTLE_MECHANIC_KEY_ITEMS(1)
#define ITEM_Z_POWER_RING SECTION_BATTLE_MECHANIC_KEY_ITEMS(2)
#define ITEM_DYNAMAX_BAND SECTION_BATTLE_MECHANIC_KEY_ITEMS(3)

// Misc. Key Items
#define SECTION_MISC_KEY_ITEMS(x) (x + SECTION_BATTLE_MECHANIC_KEY_ITEMS(3))
#define ITEM_BICYCLE SECTION_MISC_KEY_ITEMS(1)
#define ITEM_MACH_BIKE SECTION_MISC_KEY_ITEMS(2)
#define ITEM_ACRO_BIKE SECTION_MISC_KEY_ITEMS(3)
#define ITEM_OLD_ROD SECTION_MISC_KEY_ITEMS(4)
#define ITEM_GOOD_ROD SECTION_MISC_KEY_ITEMS(5)
#define ITEM_SUPER_ROD SECTION_MISC_KEY_ITEMS(6)
#define ITEM_DOWSING_MACHINE SECTION_MISC_KEY_ITEMS(7)
#define ITEM_ITEMFINDER ITEM_DOWSING_MACHINE // Pre-Gen IV name
#define ITEM_DOWSING_MCHN ITEM_DOWSING_MACHINE // Gen IV-V name
#define ITEM_TOWN_MAP SECTION_MISC_KEY_ITEMS(8)
#define ITEM_VS_SEEKER SECTION_MISC_KEY_ITEMS(9)
#define ITEM_TM_CASE SECTION_MISC_KEY_ITEMS(10)
#define ITEM_BERRY_POUCH SECTION_MISC_KEY_ITEMS(11)
#define ITEM_POKEMON_BOX_LINK SECTION_MISC_KEY_ITEMS(12)
#define ITEM_POKEMON_BOX ITEM_POKEMON_BOX_LINK // Pre-Gen VIII name
#define ITEM_COIN_CASE SECTION_MISC_KEY_ITEMS(13)
#define ITEM_POWDER_JAR SECTION_MISC_KEY_ITEMS(14)
#define ITEM_WAILMER_PAIL SECTION_MISC_KEY_ITEMS(15)
#define ITEM_POKE_RADAR SECTION_MISC_KEY_ITEMS(16)
#define ITEM_POKEBLOCK_CASE SECTION_MISC_KEY_ITEMS(17)
#define ITEM_SOOT_SACK SECTION_MISC_KEY_ITEMS(18)
#define ITEM_POKE_FLUTE SECTION_MISC_KEY_ITEMS(19)
#define ITEM_FAME_CHECKER SECTION_MISC_KEY_ITEMS(20)
#define ITEM_TEACHY_TV SECTION_MISC_KEY_ITEMS(21)

// Story Key Items
#define SECTION_STORY_KEY_ITEMS(x) (x + SECTION_MISC_KEY_ITEMS(21))
#define ITEM_SS_TICKET SECTION_STORY_KEY_ITEMS(1)
#define ITEM_EON_TICKET SECTION_STORY_KEY_ITEMS(2)
#define ITEM_MYSTIC_TICKET SECTION_STORY_KEY_ITEMS(3)
#define ITEM_AURORA_TICKET SECTION_STORY_KEY_ITEMS(4)
#define ITEM_OLD_SEA_MAP SECTION_STORY_KEY_ITEMS(5)
#define ITEM_LETTER SECTION_STORY_KEY_ITEMS(6)
#define ITEM_DEVON_PARTS SECTION_STORY_KEY_ITEMS(7)
#define ITEM_DEVON_GOODS ITEM_DEVON_PARTS // Pre-Gen VI name
#define ITEM_GO_GOGGLES SECTION_STORY_KEY_ITEMS(8)
#define ITEM_DEVON_SCOPE SECTION_STORY_KEY_ITEMS(9)
#define ITEM_BASEMENT_KEY SECTION_STORY_KEY_ITEMS(10)
#define ITEM_SCANNER SECTION_STORY_KEY_ITEMS(11)
#define ITEM_STORAGE_KEY SECTION_STORY_KEY_ITEMS(12)
#define ITEM_KEY_TO_ROOM_1 SECTION_STORY_KEY_ITEMS(13)
#define ITEM_RM_1_KEY ITEM_KEY_TO_ROOM_1 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_2 SECTION_STORY_KEY_ITEMS(14)
#define ITEM_RM_2_KEY ITEM_KEY_TO_ROOM_2 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_4 SECTION_STORY_KEY_ITEMS(15)
#define ITEM_RM_4_KEY ITEM_KEY_TO_ROOM_4 // Pre-Gen VI name
#define ITEM_KEY_TO_ROOM_6 SECTION_STORY_KEY_ITEMS(16)
#define ITEM_RM_6_KEY ITEM_KEY_TO_ROOM_6 // Pre-Gen VI name
#define ITEM_METEORITE SECTION_STORY_KEY_ITEMS(17)
#define ITEM_MAGMA_EMBLEM SECTION_STORY_KEY_ITEMS(18)
#define ITEM_CONTEST_PASS SECTION_STORY_KEY_ITEMS(19)
#define ITEM_PARCEL SECTION_STORY_KEY_ITEMS(20)
#define ITEM_OAKS_PARCEL ITEM_PARCEL // Pre-Gen IV name
#define ITEM_SECRET_KEY SECTION_STORY_KEY_ITEMS(21)
#define ITEM_BIKE_VOUCHER SECTION_STORY_KEY_ITEMS(22)
#define ITEM_GOLD_TEETH SECTION_STORY_KEY_ITEMS(23)
#define ITEM_CARD_KEY SECTION_STORY_KEY_ITEMS(24)
#define ITEM_LIFT_KEY SECTION_STORY_KEY_ITEMS(25)
#define ITEM_SILPH_SCOPE SECTION_STORY_KEY_ITEMS(26)
#define ITEM_TRI_PASS SECTION_STORY_KEY_ITEMS(27)
#define ITEM_RAINBOW_PASS SECTION_STORY_KEY_ITEMS(28)
#define ITEM_TEA SECTION_STORY_KEY_ITEMS(29)
#define ITEM_RUBY SECTION_STORY_KEY_ITEMS(30)
#define ITEM_SAPPHIRE SECTION_STORY_KEY_ITEMS(31)

// GEN IX ITEMS
#define SECTION_GEN_IX_ITEMS(x) (x + SECTION_STORY_KEY_ITEMS(31))
#define ITEM_ABILITY_SHIELD SECTION_GEN_IX_ITEMS(1)
#define ITEM_CLEAR_AMULET SECTION_GEN_IX_ITEMS(2)
#define ITEM_PUNCHING_GLOVE SECTION_GEN_IX_ITEMS(3)
#define ITEM_COVERT_CLOAK SECTION_GEN_IX_ITEMS(4)
#define ITEM_LOADED_DICE SECTION_GEN_IX_ITEMS(5)
#define ITEM_AUSPICIOUS_ARMOR SECTION_GEN_IX_ITEMS(6)
#define ITEM_BOOSTER_ENERGY SECTION_GEN_IX_ITEMS(7)
#define ITEM_BIG_BAMBOO_SHOOT SECTION_GEN_IX_ITEMS(8)
#define ITEM_GIMMIGHOUL_COIN SECTION_GEN_IX_ITEMS(9)
#define ITEM_LEADERS_CREST SECTION_GEN_IX_ITEMS(10)
#define ITEM_MALICIOUS_ARMOR SECTION_GEN_IX_ITEMS(11)
#define ITEM_MIRROR_HERB SECTION_GEN_IX_ITEMS(12)
#define ITEM_SCROLL_OF_DARKNESS SECTION_GEN_IX_ITEMS(13)
#define ITEM_SCROLL_OF_WATERS SECTION_GEN_IX_ITEMS(14)
#define ITEM_TERA_ORB SECTION_GEN_IX_ITEMS(15)
#define ITEM_TINY_BAMBOO_SHOOT SECTION_GEN_IX_ITEMS(16)

#define ITEM_BUG_TERA_SHARD SECTION_GEN_IX_ITEMS(17)
#define ITEM_DARK_TERA_SHARD SECTION_GEN_IX_ITEMS(18)
#define ITEM_DRAGON_TERA_SHARD SECTION_GEN_IX_ITEMS(19)
#define ITEM_ELECTRIC_TERA_SHARD SECTION_GEN_IX_ITEMS(20)
#define ITEM_FAIRY_TERA_SHARD SECTION_GEN_IX_ITEMS(21)
#define ITEM_FIGHTING_TERA_SHARD SECTION_GEN_IX_ITEMS(22)
#define ITEM_FIRE_TERA_SHARD SECTION_GEN_IX_ITEMS(23)
#define ITEM_FLYING_TERA_SHARD SECTION_GEN_IX_ITEMS(24)
#define ITEM_GHOST_TERA_SHARD SECTION_GEN_IX_ITEMS(25)
#define ITEM_GRASS_TERA_SHARD SECTION_GEN_IX_ITEMS(26)
#define ITEM_GROUND_TERA_SHARD SECTION_GEN_IX_ITEMS(27)
#define ITEM_ICE_TERA_SHARD SECTION_GEN_IX_ITEMS(28)
#define ITEM_NORMAL_TERA_SHARD SECTION_GEN_IX_ITEMS(29)
#define ITEM_POISON_TERA_SHARD SECTION_GEN_IX_ITEMS(30)
#define ITEM_PSYCHIC_TERA_SHARD SECTION_GEN_IX_ITEMS(31)
#define ITEM_ROCK_TERA_SHARD SECTION_GEN_IX_ITEMS(32)
#define ITEM_STEEL_TERA_SHARD SECTION_GEN_IX_ITEMS(33)
#define ITEM_WATER_TERA_SHARD SECTION_GEN_IX_ITEMS(34)

#define ITEM_ADAMANT_CRYSTAL SECTION_GEN_IX_ITEMS(35)
#define ITEM_GRISEOUS_CORE SECTION_GEN_IX_ITEMS(36)
#define ITEM_LUSTROUS_GLOBE SECTION_GEN_IX_ITEMS(37)

#define ITEM_BLACK_AUGURITE SECTION_GEN_IX_ITEMS(38)
#define ITEM_LINKING_CORD SECTION_GEN_IX_ITEMS(39)
#define ITEM_PEAT_BLOCK SECTION_GEN_IX_ITEMS(40)
#define ITEM_BERSERK_GENE SECTION_GEN_IX_ITEMS(41)

#define ITEM_FAIRY_FEATHER SECTION_GEN_IX_ITEMS(42)
#define ITEM_SYRUPY_APPLE SECTION_GEN_IX_ITEMS(43)
#define ITEM_UNREMARKABLE_TEACUP SECTION_GEN_IX_ITEMS(44)
#define ITEM_MASTERPIECE_TEACUP SECTION_GEN_IX_ITEMS(45)
#define ITEM_CORNERSTONE_MASK SECTION_GEN_IX_ITEMS(46)
#define ITEM_WELLSPRING_MASK SECTION_GEN_IX_ITEMS(47)
#define ITEM_HEARTHFLAME_MASK SECTION_GEN_IX_ITEMS(48)
#define ITEM_HEALTH_MOCHI SECTION_GEN_IX_ITEMS(49)
#define ITEM_MUSCLE_MOCHI SECTION_GEN_IX_ITEMS(50)
#define ITEM_RESIST_MOCHI SECTION_GEN_IX_ITEMS(51)
#define ITEM_GENIUS_MOCHI SECTION_GEN_IX_ITEMS(52)
#define ITEM_CLEVER_MOCHI SECTION_GEN_IX_ITEMS(53)
#define ITEM_SWIFT_MOCHI SECTION_GEN_IX_ITEMS(54)
#define ITEM_FRESH_START_MOCHI SECTION_GEN_IX_ITEMS(55)
#define ITEM_GLIMMERING_CHARM SECTION_GEN_IX_ITEMS(56)
#define ITEM_METAL_ALLOY SECTION_GEN_IX_ITEMS(57)
#define ITEM_STELLAR_TERA_SHARD SECTION_GEN_IX_ITEMS(58)

#define ITEM_JUBILIFE_MUFFIN SECTION_GEN_IX_ITEMS(59)
#define ITEM_REMEDY SECTION_GEN_IX_ITEMS(60)
#define ITEM_FINE_REMEDY SECTION_GEN_IX_ITEMS(61)
#define ITEM_SUPERB_REMEDY SECTION_GEN_IX_ITEMS(62)
#define ITEM_AUX_EVASION SECTION_GEN_IX_ITEMS(63)
#define ITEM_AUX_GUARD SECTION_GEN_IX_ITEMS(64)
#define ITEM_AUX_POWER SECTION_GEN_IX_ITEMS(65)
#define ITEM_AUX_POWERGUARD SECTION_GEN_IX_ITEMS(66)
#define ITEM_CHOICE_DUMPLING SECTION_GEN_IX_ITEMS(67)
#define ITEM_SWAP_SNACK SECTION_GEN_IX_ITEMS(68)
#define ITEM_TWICE_SPICED_RADISH SECTION_GEN_IX_ITEMS(69)
#define ITEM_POKESHI_DOLL SECTION_GEN_IX_ITEMS(70)

// HOPO BERRY
// LEGEND PLATE

#define ITEMS_COUNT SECTION_GEN_IX_ITEMS(70)
#define ITEM_FIELD_ARROW ITEMS_COUNT

// A special item id associated with "Cancel"/"Exit" etc. in a list of items or decorations
// Its icon is defined at ITEMS_COUNT as the "return to field" arrow
#define ITEM_LIST_END 0xFFFF

// Range of berries given out by various NPCS
#define FIRST_BERRY_MASTER_BERRY      ITEM_POMEG_BERRY
#define LAST_BERRY_MASTER_BERRY       ITEM_NOMEL_BERRY
#define FIRST_BERRY_MASTER_WIFE_BERRY ITEM_CHERI_BERRY
#define LAST_BERRY_MASTER_WIFE_BERRY  ITEM_SITRUS_BERRY
#define FIRST_KIRI_BERRY              ITEM_POMEG_BERRY
#define LAST_KIRI_BERRY               ITEM_NOMEL_BERRY
#define FIRST_ROUTE_114_MAN_BERRY     ITEM_RAZZ_BERRY
#define LAST_ROUTE_114_MAN_BERRY      ITEM_PINAP_BERRY

#define NUM_BERRY_MASTER_BERRIES          (LAST_BERRY_MASTER_BERRY - FIRST_BERRY_MASTER_BERRY + 1)
#define NUM_BERRY_MASTER_BERRIES_SKIPPED  (FIRST_BERRY_MASTER_BERRY - FIRST_BERRY_INDEX)
#define NUM_BERRY_MASTER_WIFE_BERRIES     (LAST_BERRY_MASTER_WIFE_BERRY - FIRST_BERRY_MASTER_WIFE_BERRY + 1)
#define NUM_KIRI_BERRIES                  (LAST_KIRI_BERRY - FIRST_KIRI_BERRY + 1)
#define NUM_KIRI_BERRIES_SKIPPED          (FIRST_KIRI_BERRY - FIRST_BERRY_INDEX)
#define NUM_ROUTE_114_MAN_BERRIES         (LAST_ROUTE_114_MAN_BERRY - FIRST_ROUTE_114_MAN_BERRY + 1)
#define NUM_ROUTE_114_MAN_BERRIES_SKIPPED (FIRST_ROUTE_114_MAN_BERRY - FIRST_BERRY_INDEX)

#define ITEM_TO_BERRY(itemId)(((itemId) - FIRST_BERRY_INDEX) + 1)
#define ITEM_TO_MAIL(itemId)((itemId) - FIRST_MAIL_INDEX)
#define MAIL_NONE 0xFF
#define ITEM_TO_MULCH(itemId)(((itemId) - ITEM_GROWTH_MULCH) + 1)

#define NUM_TECHNICAL_MACHINES 100
#define NUM_HIDDEN_MACHINES SECTION_TMS_HMS_END - SECTION_TMS_HMS(0) - NUM_TECHNICAL_MACHINES

#define MAX_BAG_ITEM_CAPACITY         999
#define MAX_PC_ITEM_CAPACITY          999
#define MAX_PYRAMID_BAG_ITEM_CAPACITY  99 // Values higher than 255 require free SaveBlock2 space.

#define MAX_ITEM_DIGITS         ((MAX_BAG_ITEM_CAPACITY > 99) ? 3 : 2)
#define MAX_PYRAMID_ITEM_DIGITS ((MAX_PYRAMID_BAG_ITEM_CAPACITY > 99) ? 3 : 2)

// Secondary IDs for rods
#define OLD_ROD   0
#define GOOD_ROD  1
#define SUPER_ROD 2

// Secondary IDs for bikes
#define MACH_BIKE 0
#define ACRO_BIKE 1

// Item parameters for EXP Candies
#define EXP_100   1
#define EXP_800   2
#define EXP_3000  3
#define EXP_10000 4
#define EXP_30000 5

// Item type IDs (used to determine the exit callback)
#define ITEM_USE_MAIL             0
#define ITEM_USE_PARTY_MENU       1
#define ITEM_USE_FIELD            2
#define ITEM_USE_PBLOCK_CASE      3
#define ITEM_USE_BAG_MENU         4 // No exit callback, stays in bag menu
#define ITEM_USE_PARTY_MENU_MOVES 5

// Item battle script IDs (need to be non-zero)
#define EFFECT_ITEM_RESTORE_HP              1
#define EFFECT_ITEM_CURE_STATUS             2
#define EFFECT_ITEM_HEAL_AND_CURE_STATUS    3
#define EFFECT_ITEM_INCREASE_STAT           4
#define EFFECT_ITEM_SET_MIST                5
#define EFFECT_ITEM_SET_FOCUS_ENERGY        6
#define EFFECT_ITEM_ESCAPE                  7
#define EFFECT_ITEM_THROW_BALL              8
#define EFFECT_ITEM_REVIVE                  9
#define EFFECT_ITEM_RESTORE_PP              10
#define EFFECT_ITEM_INCREASE_ALL_STATS      11

// Enigma Berry dummy constant
#define EFFECT_ITEM_ENIGMA_BERRY_EREADER    1

#endif  // GUARD_CONSTANTS_ITEMS_H
